### ISSUE TITLE
compile error: recipe for target 'world' failed

### ISSUE THREAD

**Issue by ZERO-A-ONE** [olegkutkov/starlink-wifi-gen2#3]
When I was compiling, I encountered some problems：

```
make: *** [world] Error 1
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
/starlink-wifi-mtk/openwrt/include/toplevel.mk:197: recipe for target 'world' failed
+ chown -R ubuntu:UnixUsers .
chown: invalid group: ‘ubuntu:UnixUsers’
```

**Comment by ZERO-A-ONE** [comment]
I fixed this issue and need to fix zlib located at `openwrt/package/libs/zlib/Makefile`:

PKG_VERSION:=1.2.13
PKG_HASH:= d14c38e313afc35a9a8760dadf26042f51ea0f5d154b0630a31da0540107fb98

Please refer to: http://www.zlib.net/

**Comment by freako7c5** [comment]
Hi @ZERO-A-ONE, does this fix for the issue still work now?

**Comment by ZERO-A-ONE** [comment]
> Hi @ZERO-A-ONE, does this fix for the issue still work now?

Unfortunately, after addressing this issue, I still encountered numerous problems during the compilation process, and ultimately, I gave up.
